/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Motor_L_EN.c
**     Project   : Project
**     Processor : MC9S12C32MFA25
**     Component : BitsIO
**     Version   : Component 02.102, Driver 03.14, CPU db: 2.87.402
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 3/19/2019, 7:45 PM
**     Abstract  :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**     Settings  :
**         Port name                   : T
**
**         Bit mask of the port        : $0003
**         Number of bits/pins         : 2
**         Single bit numbers          : 0 to 1
**         Values range                : 0 to 3
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PTT       [$0240]
**         Port control register       : DDRT      [$0242]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    1    |   PT0_PWM0_IOC0
**                    1      |    2    |   PT1_PWM1_IOC1
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents  :
**         GetDir - bool Motor_L_EN_GetDir(void);
**         SetDir - void Motor_L_EN_SetDir(bool Dir);
**         GetVal - byte Motor_L_EN_GetVal(void);
**         PutVal - void Motor_L_EN_PutVal(byte Val);
**         GetBit - bool Motor_L_EN_GetBit(byte Bit);
**         PutBit - void Motor_L_EN_PutBit(byte Bit, bool Val);
**         SetBit - void Motor_L_EN_SetBit(byte Bit);
**         ClrBit - void Motor_L_EN_ClrBit(byte Bit);
**         NegBit - void Motor_L_EN_NegBit(byte Bit);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Motor_L_EN. */

#include "Motor_L_EN.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG Motor_L_EN_DATA       /* Select data segment "Motor_L_EN_DATA" */
#pragma CODE_SEG Motor_L_EN_CODE
#pragma CONST_SEG Motor_L_EN_CONST     /* Constant section for this module */
/*
** ===================================================================
**     Method      :  Motor_L_EN_GetMsk (component BitsIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const byte Motor_L_EN_Table[2U] = { /* Table of mask constants */
   0x01U, 0x02U
};

static byte Motor_L_EN_GetMsk (byte PinIndex)
{
  return (byte)((PinIndex<2U) ? Motor_L_EN_Table[PinIndex] : 0U); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  Motor_L_EN_GetVal (component BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 3)
** ===================================================================
*/
byte Motor_L_EN_GetVal(void)
{
  return (byte)(getReg8(PTT) & 0x03U); /* Return port data */
}

/*
** ===================================================================
**     Method      :  Motor_L_EN_PutVal (component BitsIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pins
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
void Motor_L_EN_PutVal(byte Val)
{
  Val &= 0x03U;                        /* Mask output value */
  Shadow_T = (byte)((Shadow_T & 0xFCU) | Val); /* Set-up shadow variable */
  setReg8(PTT, (getReg8(PTT) & (byte)(~(byte)0x03U)) | Val); /* Put masked value on port */
}

/*
** ===================================================================
**     Method      :  Motor_L_EN_GetBit (component BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 1)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool Motor_L_EN_GetBit(byte Bit)
{
  byte const Mask = Motor_L_EN_GetMsk(Bit); /* Temporary variable - bit mask to test */
  return (bool)(((getReg8(PTT) & Mask) == Mask)? 1U: 0U); /* Test if specified bit of port register is set */
}

/*
** ===================================================================
**     Method      :  Motor_L_EN_PutBit (component BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**           a) direction = Input  : sets the value of the specified
**                                   bit; this operation will be
**                                   shown on output after the
**                                   direction has been switched to
**                                   output (SetDir(TRUE);)
**           b) direction = Output : directly writes the value of the
**                                   bit to the appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 1)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void Motor_L_EN_PutBit(byte Bit, bool Val)
{
  byte const Mask = Motor_L_EN_GetMsk(Bit); /* Temporary variable - put bit mask */
  if (Val) {
    setReg8Bits(PTT, Mask);            /* [bit (Bit)]=0x01U */
    Shadow_T |= Mask;                  /* Set appropriate bit in shadow variable */
  } else { /* !Val */
    clrReg8Bits(PTT, Mask);            /* [bit (Bit)]=0x00U */
    Shadow_T &= (byte)~(byte)Mask;     /* Clear appropriate bit in shadow variable */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  Motor_L_EN_ClrBit (component BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**           a) direction = Input  : sets the specified bit to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   beenswitched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 1)
**     Returns     : Nothing
** ===================================================================
*/
void Motor_L_EN_ClrBit(byte Bit)
{
  byte const Mask = Motor_L_EN_GetMsk(Bit); /* Temporary variable - set bit mask */
  clrReg8Bits(PTT, Mask);              /* [bit (Bit)]=0x00U */
  Shadow_T &= (byte)~(byte)Mask;       /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Motor_L_EN_SetBit (component BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**           a) direction = Input  : sets the specified bit to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 1)
**     Returns     : Nothing
** ===================================================================
*/
void Motor_L_EN_SetBit(byte Bit)
{
  byte const Mask = Motor_L_EN_GetMsk(Bit); /* Temporary variable - set bit mask */
  setReg8Bits(PTT, Mask);              /* [bit (Bit)]=0x01U */
  Shadow_T |= Mask;                    /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Motor_L_EN_NegBit (component BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**           a) direction = Input  : inverts the specified bit;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly inverts the value
**                                   of the appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void Motor_L_EN_NegBit(byte Bit)
{
  byte const Mask = Motor_L_EN_GetMsk(Bit); /* Temporary variable - set bit mask */
  invertReg8Bits(PTT, Mask);           /* [bit (Bit)]=invert */
  Shadow_T ^= Mask;                    /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Motor_L_EN_GetDir (component BitsIO)
**
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
/*
bool Motor_L_EN_GetDir(void)

**  This method is implemented as a macro. See Motor_L_EN.h file.  **
*/

/*
** ===================================================================
**     Method      :  Motor_L_EN_SetDir (component BitsIO)
**
**     Description :
**         This method sets direction of the component.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void Motor_L_EN_SetDir(bool Dir)
{
  if (Dir) {
    setReg8(PTT, (getReg8(PTT) & (byte)(~(byte)0x03U)) | (Shadow_T & 0x03U)); /* Put masked value on port */
    /* DDRT: DDRT1=1,DDRT0=1 */
    setReg8Bits(DDRT, 0x03U);           
  } else { /* !Dir */
    /* DDRT: DDRT1=0,DDRT0=0 */
    clrReg8Bits(DDRT, 0x03U);           
  } /* !Dir */
}


/* END Motor_L_EN. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
