/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Motor_L_Drive8.c
**     Project   : Project
**     Processor : MC9S12C32MFA25
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.15, CPU db: 2.87.402
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 3/19/2019, 7:45 PM
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       8             |  PT5_IOC5
**             ----------------------------------------------------
**
**         Port name                   : T
**
**         Bit number (in port)        : 5
**         Bit mask of the port        : $0020
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PTT       [$0240]
**         Port control register       : DDRT      [$0242]
**
**         Optimization for            : speed
**     Contents  :
**         SetDir - void Motor_L_Drive8_SetDir(bool Dir);
**         GetVal - bool Motor_L_Drive8_GetVal(void);
**         PutVal - void Motor_L_Drive8_PutVal(bool Val);
**         ClrVal - void Motor_L_Drive8_ClrVal(void);
**         SetVal - void Motor_L_Drive8_SetVal(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Motor_L_Drive8. */

#include "Motor_L_Drive8.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG Motor_L_Drive8_DATA   /* Select data segment "Motor_L_Drive8_DATA" */
#pragma CODE_SEG Motor_L_Drive8_CODE
#pragma CONST_SEG Motor_L_Drive8_CONST /* Constant section for this module */
/*
** ===================================================================
**     Method      :  Motor_L_Drive8_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool Motor_L_Drive8_GetVal(void)

**  This method is implemented as a macro. See Motor_L_Drive8.h file.  **
*/

/*
** ===================================================================
**     Method      :  Motor_L_Drive8_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void Motor_L_Drive8_PutVal(bool Val)
{
  if (Val) {
    setReg8Bits(PTT, 0x20U);           /* PTT5=0x01U */
    Shadow_T |= 0x20U;                 /* Set-up shadow variable */
  } else { /* !Val */
    clrReg8Bits(PTT, 0x20U);           /* PTT5=0x00U */
    Shadow_T &= 0xDFU;                 /* Set-up shadow variable */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  Motor_L_Drive8_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**           a) direction = Input  : sets the output value to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Motor_L_Drive8_ClrVal(void)

**  This method is implemented as a macro. See Motor_L_Drive8.h file.  **
*/

/*
** ===================================================================
**     Method      :  Motor_L_Drive8_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**           a) direction = Input  : sets the output value to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Motor_L_Drive8_SetVal(void)

**  This method is implemented as a macro. See Motor_L_Drive8.h file.  **
*/

/*
** ===================================================================
**     Method      :  Motor_L_Drive8_SetDir (component BitIO)
**
**     Description :
**         This method sets direction of the component.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void Motor_L_Drive8_SetDir(bool Dir)
{
  if (Dir) {
    setReg8(PTT, (getReg8(PTT) & (byte)(~(byte)0x20U)) | (Shadow_T & 0x20U)); /* PTT5=Shadow_T[bit 5] */
    setReg8Bits(DDRT, 0x20U);          /* DDRT5=0x01U */
  } else { /* !Dir */
    clrReg8Bits(DDRT, 0x20U);          /* DDRT5=0x00U */
  } /* !Dir */
}


/* END Motor_L_Drive8. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
